language: julia
julia:
  - 0.4
  - nightly
git:
  depth: 99999999
before_install:
  - sudo apt-get update -qq;
    eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64";
script:
    - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("Neovim")'
